dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.140.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.140.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.140.0
  - gomod: github.com/myuser/simpleprocessor v0.0.1
    path: ./myprocessor

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.140.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
